-- Run this once in Supabase Dashboard > SQL Editor.
-- All tables are backend-only: anon/authenticated clients receive no access.

create table if not exists public.subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  phone text,
  created_at timestamptz not null default now(),
  consent_version text not null
);

create table if not exists public.admin_sessions (
  token_hash text primary key,
  expires_at bigint not null
);

create table if not exists public.request_limits (
  key text primary key,
  count integer not null,
  expires_at bigint not null
);

alter table public.subscribers enable row level security;
alter table public.admin_sessions enable row level security;
alter table public.request_limits enable row level security;

revoke all on table public.subscribers from anon, authenticated;
revoke all on table public.admin_sessions from anon, authenticated;
revoke all on table public.request_limits from anon, authenticated;

grant select, insert, update, delete on table public.subscribers to service_role;
grant select, insert, update, delete on table public.admin_sessions to service_role;
grant select, insert, update, delete on table public.request_limits to service_role;
grant usage, select on sequence public.subscribers_id_seq to service_role;

create or replace function public.consume_request_limit(
  p_key text,
  p_now bigint,
  p_expires_at bigint
) returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  next_count integer;
begin
  insert into public.request_limits (key, count, expires_at)
  values (p_key, 1, p_expires_at)
  on conflict (key) do update set
    count = case
      when public.request_limits.expires_at < p_now then 1
      else public.request_limits.count + 1
    end,
    expires_at = case
      when public.request_limits.expires_at < p_now then p_expires_at
      else public.request_limits.expires_at
    end
  returning count into next_count;

  delete from public.request_limits
  where expires_at < p_now and key <> p_key;

  return next_count;
end;
$$;

revoke all on function public.consume_request_limit(text, bigint, bigint) from public, anon, authenticated;
grant execute on function public.consume_request_limit(text, bigint, bigint) to service_role;
